apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: hello-world-prod
commonLabels:
  environment: production

replacements:
  - sourceValue: production
    targets:
      - select:
          kind: DatadogMonitor
        fieldPaths:
          - spec.tags.0
        options:
          delimiter: ":"
          index: 1

patches:
  - target:
      kind: Gateway
      name: hello-python-gateway
    patch: |
      - op: replace
        path: /spec/listeners/0/hostname
        value: hello-python.example.com
  - target:
      kind: HTTPRoute
      name: hello-python
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: hello-python.example.com
